### ISSUE TITLE
`ValueError: bad marshal data (unknown type code)` when calling `get_keras_model()`

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/autovi#3]
`get_keras_model()` incompatibility issue.

```r
checker <- auto_vi(fitted_model = lm(dist ~ speed, data = cars), 
                   keras_model = get_keras_model("vss_phn_32"))
> reticulate::py_last_error()
── Python Exception Message ────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Users/cookd/.virtualenvs/r-reticulate/lib/python3.9/site-packages/keras/src/saving/saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/Users/cookd/.virtualenvs/r-reticulate/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/cookd/.virtualenvs/r-reticulate/lib/python3.9/site-packages/keras/src/utils/generic_utils.py", line 102, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
── R Traceback ─────────────────────────────────────────────────────────────
    ▆
 1. ├─autovi::auto_vi(...)
 2. │ └─AUTO_VI$instantiate(...)
 3. │   └─env$..init..(...)
 4. └─autovi::get_keras_model("vss_phn_32")
 5.   └─keras$models$load_model(...)
 6.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
 See `reticulate::py_last_error()$r_trace$full_call` for more details.
```

**Comment by TengMCing** [comment]
solved by providing the script to rebuild the Keras model locally
